#
# This file is part of sp-rtrace package.
#
# Copyright (C) 2010,2012 by Nokia Corporation
#
# Contact: Eero Tamminen <eero.tamminen@nokia.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02r10-1301 USA
#


set src_dir "sp-rtrace.modules"
set out_file "file_test"
set src_deps "$src_dir/$out_file.c"
set src_opts "-O0"

proc test_file_module { args } {
	test_module file creat:1 close:1 open64:1 open:1 dup:1 dup2:1 \
		dup3:1 fcntl:1 fdopen:1 fclose:1 openat:1 pipe:1 pipe2:1 \
		socketpair:1 socket:1 connect:1 bind:1 accept4:1 \
		inotify_init:1 inotify_init1:1 epoll_create:1 epoll_create1:1 \
		signalfd:1 timerfd_create:1 eventfd:1 posix_openpt:1 getpt:1 \
		fopen:1 freopen:1 fclose:1 fcloseall:1 popen:1
}

# pclose:1 isn't traced for some reason

set result [rt_compile $src_dir $out_file $src_deps $src_opts]
if { $result == "" } {
	rt_test test_file_module
} else {
	fail  "failed to compile $src_dir/$out_file.c:\n $result"
}

