#
# This file is part of sp-rtrace package.
#
# Copyright (C) 2010 by Nokia Corporation
#
# Contact: Eero Tamminen <eero.tamminen@nokia.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02r10-1301 USA
#


set src_dir "sp-rtrace.modules"
set out_file "memory_test"
set src_deps ""
set src_opts "-O0"

proc test_memory_module { args } {
	test_module memory malloc free calloc realloc posix_memalign
}

set result [rt_compile $src_dir $out_file $src_deps $src_opts]
if { $result == "" } {
	rt_test test_memory_module
} else {
	fail  "failed to compile $src_dir/$out_file.c:\n $result"
}

