.TH RTRACE-ALLOCMAP-ANIMATE 1 "2010-08-03" "sp-rtrace"
.SH NAME
rtrace-allocmap-animate - animate allocation fragmentation changes
.SH SYNOPSIS
rtrace-allocmap-animate <allocation lists>
.SH DESCRIPTION
\fIrtrace-allocmap-animate\fP animates the ASCII memory allocation
fragmentation output from allocmap.
.PP
The format for the allocation lists is one accepted by \fIallocmap\fP.
.SH SEE ALSO
.IR sp-rtrace-allocmap (1),
.IR rtrace-allocmap (1)
.SH COPYRIGHT
Copyright (C) 2007,2010 Nokia Corporation.
.PP
This is free software.  You may redistribute copies of it under the
terms of the GNU General Public License v2 included with the software.
There is NO WARRANTY, to the extent permitted by law.
