#
# This file is part of sp-rtrace package.
#
# Copyright (C) 2010 by Nokia Corporation
#
# Contact: Eero Tamminen <eero.tamminen@nokia.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02r10-1301 USA
#


set src_dir "sp-rtrace.resolve"
set out_file "resolve_test_debug"
set src_deps "$src_dir/resolve_test.c"
set src_opts "-O0"

proc check_resolve_debug { args } {
	set index 0
	set rc 0
	spawn sp-rtrace -e memory -P-r -s -x $::bin_dir/$::out_file
	expect {
		-re {(?n)^\t0x[0-9a-fA-F]+ \(([^\r\n]+)\)[\r\n]$} {
			if { ![regexp {^in ([^ ]+) at ([^/]+)$} $expect_out(1,string) match name source] } {
				fail "couldn't parse backtrace record: $expect_out(1,string)"
				exp_close
				exp_wait
				return -1
			}
			set out_name [lindex $args $index]
			set out_source "resolve_test.c:[lindex $args [expr $index + 1]]"
			if { $out_name == "*"} {
				exp_close
			} else {
				if { $name != $out_name } {
					fail "expected function: $out_name, but got: $name"
					set rc -1			
				}
				if { $out_source != "resolve_test.c:*" && $source != $out_source } {
					fail "expected source location: $out_source, but got: $source"
					set rc -1			
				}
				set index [expr $index + 2]
				exp_continue
			}
		}
	}
	exp_wait
	return $rc
}

proc test_resolve_debug { args } {
	if { [check_resolve_debug zero 34 one 40 two 45 start 50 "*" "*"] == 0 } {
		pass "resolving with debug symbols"
	}
}

set result [rt_compile $src_dir $out_file $src_deps $src_opts]
if { $result == "" } {
	rt_test test_resolve_debug
} else {
	fail  "failed to compile $src_dir/$out_file.c:\n $result"
}

