#!/bin/sh
#
# Script for renaming rtrace output files.
# This file is part of sp-rtrace.
#
# Copyright (C) 2006,2010 by Nokia Corporation
#
# Contact: Eero Tamminen <eero.tamminen@nokia.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 
# version 2 as published by the Free Software Foundation. 
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301 USA
#
# Originally this file was a part of libleaks package, but moved
# to the sp-rtrace package during libleaks redesign.
#

#
# Renames files matching specified pattern by replacing $pid with $name
#
rename_pattern()
{	
	files=$(ls $1 2>/dev/null)
	if [ -n "$files" ]; then
		for i in $files 
		do
			new_file=$(echo $i | sed "s/$pid\([.-]\)/$name\1/")
			if [  -e "$new_file" ]; then
				if [ -z $FORCE_OVERWRITE ]; then
					echo "Warning: target file $new_file already exists. Renaming skipped."
					continue
				fi
			fi
			mv $i $new_file
			count=$(($count+1))
		done
	fi
}

usage ()
{
	echo "Renames all (also post-processed) rtrace files"
	echo "in the current directory from format 'PID.rtrace*'"
	echo "to 'NAME.rtrace*' format."
	echo
	echo "If --force is specified existing files (if any) will"
	echo "be overwritten."
	echo
	echo "If --binary is specified, just prefix names of the files"
	echo "with the binary name found in the file itself.  This"
	echo "option works only in ASCII format traces (*.rtrace.txt)."
	echo
	echo "usage:"
	echo "  ${0##*/} [--force] <PID1> <NAME1> <PID2> <NAME2> ..."
	echo "  ${0##*/} [--force] --binary"
	exit 1
}

# check command line args
if [ $# -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	usage
fi

if [ "$1" = "--force" ]; then
	FORCE_OVERWRITE=1
	shift
fi	

count=0

if [ "$1" = "--binary" ]; then
	echo "renaming trace files based on binary name in trace header..."
	for i in $(ls [0-9]*-[0-9]*.rtrace.txt); do
		name=$(head -1 $i|cut -d, -f4|cut -d= -f2)
		echo $i "->" ${name##*/}-$i
		mv $i ${name##*/}-$i
		count=$(($count+1))
	done
else
	if [ $# -lt 2 ]; then usage; fi
	echo "renaming trace files based on given PIDs and NAMEs..."
	while true
	do
		pid=$1
		[ -z "$pid" ] && break
		shift
		name=$1
		[ -z "$name" ] && break
		shift
		rename_pattern $pid.'rtrace*'
		rename_pattern $pid-'*.rtrace*'
	done
fi
echo "Renamed $count files."
exit 0
