#!/bin/sh
#
# A script for generating a console animation of memory fragmentation
# using sp-rtrace-allocmap.
#
# If you've dumped several successive allocmap input files from the same
# process run, with this you can see how the allocation or frees or leaks
# change place in the process memory within time.
#
# This file is part of sp-rtrace.
#
# Copyright (C) 2006,2010 by Nokia Corporation
#
# Contact: Eero Tamminen <eero.tamminen@nokia.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 
# version 2 as published by the Free Software Foundation. 
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301 USA
#
# Originally this file was a part of libleaks package, but moved
# to the sp-rtrace package during libleaks redesign.
#

for file in $*; do
	echo 'clear'
	echo 'cat << EOF'
	echo ${file##*/}
	cut -d' ' -f1,2 < $file | sp-rtrace-allocmap | grep '^[0 ]'
	echo 'EOF'
	echo 'usleep 100'
done
