#
# This file is part of sp-rtrace package.
#
# Copyright (C) 2010 by Nokia Corporation
#
# Contact: Eero Tamminen <eero.tamminen@nokia.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02r10-1301 USA
#

set src_dir "sp-rtrace.lib"
set out_file "context_test"
set src_deps "$src_dir/$out_file.c"
set src_opts "-L$lib_dir -lsp-rtrace1 -O3"

#
# test case for context with preloaded sp-rtrace-main module
#
proc test_context { args } {
	rt_preload_set "/usr/lib/sp-rtrace/libsp-rtrace-main.so"
	rt_run_test $::out_file
	rt_preload_clear
}

set result [rt_compile $src_dir $out_file $src_deps $src_opts]
if { $result == "" } {
	rt_test test_context
} else {
	fail  "failed to compile $src_dir/$out_file.c:\n $result"
}